# Generated by Django 3.2 on 2021-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='gallery',
            name='telephone',
            field=models.CharField(default=1111, max_length=255),
            preserve_default=False,
        ),
    ]
