# Generated by Django 3.2 on 2021-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_boat_mokoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokoro',
            name='king',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
