# Generated by Django 3.2 on 2021-05-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mokoro_king'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mokoro',
            name='king',
        ),
    ]
