# Generated by Django 3.2 on 2021-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210430_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
    ]
