# Generated by Django 3.2 on 2021-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210501_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
